#CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2
CONFIG_ZMK_STUDIO=y
CONFIG_INPUT=y

#About Prospector------------------------------
CONFIG_DONGLE_SCREEN_HORIZONTAL=y
CONFIG_DONGLE_SCREEN_FLIPPED=n
CONFIG_DONGLE_SCREEN_AMBIENT_LIGHT=n
CONFIG_DONGLE_SCREEN_IDLE_TIMEOUT_S=300
CONFIG_DONGLE_SCREEN_MAX_BRIGHTNESS=100
CONFIG_DONGLE_SCREEN_MIN_BRIGHTNESS=1
CONFIG_DONGLE_SCREEN_DEFAULT_BRIGHTNESS=30
CONFIG_DONGLE_SCREEN_BRIGHTNESS_KEYBOARD_CONTROL=y
CONFIG_DONGLE_SCREEN_BRIGHTNESS_UP_KEYCODE=115
CONFIG_DONGLE_SCREEN_BRIGHTNESS_DOWN_KEYCODE=114
CONFIG_DONGLE_SCREEN_BRIGHTNESS_STEP=1
CONFIG_LV_Z_MEM_POOL_SIZE=20000
CONFIG_DONGLE_SCREEN_BUTTONS_MONO=n
CONFIG_DONGLE_SCREEN_BUTTONS_TEXT_COLORFUL=y
CONFIG_DONGLE_SCREEN_MEDIA_ACTIVE=n
CONFIG_DONGLE_SCREEN_WPM_ACTIVE=y
CONFIG_DONGLE_SCREEN_MODIFIER_ACTIVE=y
CONFIG_DONGLE_SCREEN_LAYER_ACTIVE=y
CONFIG_DONGLE_SCREEN_OUTPUT_ACTIVE=y
CONFIG_DONGLE_SCREEN_BATTERY_ACTIVE=y
CONFIG_DONGLE_SCREEN_NAME_ACTIVE=y
CONFIG_DONGLE_SCREEN_MAIN_BUTTONS_ROW1=y
CONFIG_DONGLE_SCREEN_BONGO_CAT_ACTIVE=n
CONFIG_DONGLE_SCREEN_BONGO_BOO_ACTIVE=n
CONFIG_DONGLE_SCREEN_BONGO_SPHEAL_ACTIVE=y
CONFIG_DONGLE_SCREEN_BONGO_DOE_ACTIVE=n
#----------------------------------------------
